// One-off: remove any artist `shortBio` that was autogenerated by the WP
// import with the "<Name> released N release(s) on Hunya Munya Records ..."
// template. Adds no value — visitors can see the actual release count from
// the Discography section. metaDescription stays intact for SEO.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import matter from "gray-matter";

const ROOT = process.cwd();
const ARTISTS_DIR = resolve(ROOT, "content/artists");
const AUTOGEN = /released \d+ releases? on Hunya Munya Records/i;

for (const name of readdirSync(ARTISTS_DIR)) {
  if (!name.endsWith(".mdx")) continue;
  const path = resolve(ARTISTS_DIR, name);
  const raw = readFileSync(path, "utf8");
  const parsed = matter(raw);
  const bio = typeof parsed.data.shortBio === "string" ? parsed.data.shortBio : "";
  if (!bio || !AUTOGEN.test(bio)) continue;
  delete parsed.data.shortBio;
  const out = matter.stringify(parsed.content, parsed.data);
  writeFileSync(path, out);
  console.log(`removed autogen shortBio from ${name}`);
}
