#!/bin/bash
# Idempotent patch for two crawl defects on the already-cut-over VPS. Safe to
# re-run. Does NOT touch the certbot SSL edits: it only inserts directives into
# the existing server block and adds one new redirect-only block.
#
# Fixes:
#
#   1. www serves a full duplicate of the site at 200.
#      https://www.hunyamunyarecords.com/catalog returns the whole page instead
#      of redirecting. Every internal link is root-relative, so a crawler that
#      enters on www stays on www for all 139 pages and crawls the site twice.
#      rel=canonical does point at the apex, so Google consolidates eventually,
#      but it spends crawl budget to get there and delays indexing.
#
#   2. Every trailing-slash URL is a dead end.
#      next.config has trailingSlash:false, and `try_files $uri $uri.html $uri/`
#      tries the literal directory first. Where the export has a directory
#      (/catalog/, /artists/, /news/, /press/rykard/) autoindex is off so nginx
#      answers 403; where it does not (/about/) it answers 404. Neither is a
#      redirect, so an inbound link or a pasted URL with a trailing slash passes
#      no link equity. Repeated 403s can also throttle Googlebot.
#
# Run as root on the VPS:
#
#   curl -fsSL https://raw.githubusercontent.com/evanatpizzarobot/hunyamunya/main/site/scripts/vps-canonical-host-patch.sh | sudo bash

set -e

SITE_FILE=/etc/nginx/sites-available/hunyamunya
REDIRECT_FILE=/etc/nginx/sites-available/hunyamunya-www-redirect
BACKUP="${SITE_FILE}.bak.$(date +%Y%m%d-%H%M%S)"

if [ ! -f "$SITE_FILE" ]; then
  echo "ERROR: $SITE_FILE not found. Is this the right host?" >&2
  exit 1
fi

cp -a "$SITE_FILE" "$BACKUP"
echo "backed up $SITE_FILE -> $BACKUP"

# Roll the config back and bail if anything below leaves nginx unable to parse.
rollback() {
  echo "nginx config test FAILED, rolling back" >&2
  cp -a "$BACKUP" "$SITE_FILE"
  rm -f /etc/nginx/sites-enabled/hunyamunya-www-redirect
  nginx -t && systemctl reload nginx || true
  exit 1
}

# ---------------------------------------------------------------- 1. www ----
# Drop www from the main block so it stops answering for that host. Matches
# the server_name line whether or not certbot has reordered it.
if grep -qE '^\s*server_name[^;]*\bwww\.hunyamunyarecords\.com\b' "$SITE_FILE"; then
  sed -i -E 's/(^\s*server_name[^;]*)\s+www\.hunyamunyarecords\.com/\1/' "$SITE_FILE"
  echo "removed www from the main block's server_name"
else
  echo "main block already does not claim www, skipping"
fi

# Certbot rewrote the vhost to listen on 443 with a cert. Reuse the exact same
# cert paths for the redirect block so www keeps terminating TLS: a browser hits
# the TLS handshake before it ever sees a 301, so a redirect block without a
# valid cert produces a certificate warning rather than a redirect.
SSL_CERT=$(grep -m1 -E '^\s*ssl_certificate\s' "$SITE_FILE" | awk '{print $2}' | tr -d ';')
SSL_KEY=$(grep -m1 -E '^\s*ssl_certificate_key\s' "$SITE_FILE" | awk '{print $2}' | tr -d ';')

# Carry the certbot TLS hardening onto the redirect vhost too. Without these
# the block would fall back to nginx's built-in protocol and cipher defaults,
# so www would negotiate weaker TLS than the apex it redirects to. Emitted only
# when the main block actually references them.
SSL_EXTRA=""
if grep -qF 'options-ssl-nginx.conf' "$SITE_FILE"; then
  SSL_EXTRA="    include /etc/letsencrypt/options-ssl-nginx.conf;"
fi
if grep -qF 'ssl-dhparams.pem' "$SITE_FILE"; then
  SSL_EXTRA="${SSL_EXTRA}
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;"
fi

if [ -n "$SSL_CERT" ] && [ -n "$SSL_KEY" ]; then
  cat > "$REDIRECT_FILE" <<NGINX
# Generated by scripts/vps-canonical-host-patch.sh. Redirect-only vhost: sends
# every www request to the apex, preserving path and query.
#
# www must NOT appear in the main block's server_name at the same time as this
# exact-match block, or nginx reports a conflicting server name, keeps the
# first match (the main block), and the redirect silently never fires.
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name www.hunyamunyarecords.com;

    ssl_certificate ${SSL_CERT};
    ssl_certificate_key ${SSL_KEY};
${SSL_EXTRA}

    return 301 https://hunyamunyarecords.com\$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name www.hunyamunyarecords.com;

    return 301 https://hunyamunyarecords.com\$request_uri;
}
NGINX
  ln -sf "$REDIRECT_FILE" /etc/nginx/sites-enabled/hunyamunya-www-redirect
  echo "wrote $REDIRECT_FILE (TLS via ${SSL_CERT})"
else
  # No cert found: still worth redirecting plain http, but say so loudly,
  # because https://www would then fall through to the default server.
  cat > "$REDIRECT_FILE" <<'NGINX'
server {
    listen 80;
    listen [::]:80;
    server_name www.hunyamunyarecords.com;
    return 301 https://hunyamunyarecords.com$request_uri;
}
NGINX
  ln -sf "$REDIRECT_FILE" /etc/nginx/sites-enabled/hunyamunya-www-redirect
  echo "WARNING: no ssl_certificate found in $SITE_FILE."
  echo "WARNING: wrote an http-only www redirect. https://www will NOT redirect."
fi

# ------------------------------------------------------- 2. trailing slash ---
# Insert the redirect immediately above `location / {`, so it is evaluated
# before try_files ever gets the chance to answer 403 on a real directory.
# The query-string group uses the character class [?] rather than an escaped
# \? on purpose: awk's string lexer eats the backslash and would emit the
# invalid nginx regex (?.*), which nginx -t rejects. [?] needs no escaping and
# means exactly the same thing.
if grep -qF 'request_uri ~ ^/(.+)/([?].*)?$' "$SITE_FILE"; then
  echo "trailing-slash redirect already present, skipping"
else
  awk '
    /^[[:space:]]*location \/ \{/ && !done {
      print "    # Collapse trailing slashes to the canonical no-slash form."
      print "    # trailingSlash:false in next.config means /catalog/ has no page;"
      print "    # without this, try_files resolves the directory and answers 403."
      print "    if ($request_uri ~ ^/(.+)/([?].*)?$) { return 301 /$1$2; }"
      print ""
      done = 1
    }
    { print }
  ' "$SITE_FILE" > "${SITE_FILE}.new" && mv "${SITE_FILE}.new" "$SITE_FILE"
  echo "inserted trailing-slash redirect"
fi

# Drop the `$uri/` term so a directory can never resolve to a 403 at all.
if grep -q 'try_files \$uri \$uri.html \$uri/ =404;' "$SITE_FILE"; then
  sed -i 's|try_files \$uri \$uri.html \$uri/ =404;|try_files $uri $uri.html =404;|' "$SITE_FILE"
  echo "removed the \$uri/ directory term from try_files"
else
  echo "try_files already has no directory term, skipping"
fi

# ------------------------------------------------------------------ apply ---
nginx -t || rollback
systemctl reload nginx
echo
echo "nginx reloaded. Verify:"
echo "  curl -sI https://www.hunyamunyarecords.com/catalog | head -1   # expect 301"
echo "  curl -sI https://hunyamunyarecords.com/catalog/    | head -1   # expect 301"
echo "  curl -sI https://hunyamunyarecords.com/catalog     | head -1   # expect 200"
echo
echo "Rollback if needed:"
echo "  sudo cp -a $BACKUP $SITE_FILE"
echo "  sudo rm -f /etc/nginx/sites-enabled/hunyamunya-www-redirect"
echo "  sudo nginx -t && sudo systemctl reload nginx"
