#!/bin/bash
# VPS bootstrap: installs nginx + node, creates a `deploy` user for GitHub
# Actions SSH, lays down the web root, and writes an nginx server block for
# hunyamunyarecords.com. Run as root on a fresh Ubuntu 24.04 VPS:
#
#   curl -fsSL https://raw.githubusercontent.com/evanatpizzarobot/hunyamunya/main/site/scripts/vps-setup.sh | bash
#
# After this completes, paste your deploy-actions.pub into
# /home/deploy/.ssh/authorized_keys (one-liner shown at end of output).

set -e

apt update -qq
apt install -y nginx curl git

curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
apt install -y nodejs

useradd -m -s /bin/bash deploy || true
mkdir -p /home/deploy/.ssh
chmod 700 /home/deploy/.ssh
touch /home/deploy/.ssh/authorized_keys
chmod 600 /home/deploy/.ssh/authorized_keys
chown -R deploy:deploy /home/deploy/.ssh

mkdir -p /var/www/hunyamunya
chown -R deploy:deploy /var/www/hunyamunya

# Bootstrap the redirect snippet file so nginx can start even before the
# first deploy has rsynced the real snippet. The deploy workflow overwrites
# this file on every push to main.
touch /var/www/hunyamunya/.nginx-redirects.conf
chown deploy:deploy /var/www/hunyamunya/.nginx-redirects.conf

# Content-type-keyed Cache-Control. Keeps static assets immutable (1y) but
# forces HTML to revalidate on every hit, so content edits show up without
# needing a browser hard refresh. `map` must live in http context.
cat > /etc/nginx/conf.d/hmr-cache-control.conf <<'MAP'
map $sent_http_content_type $hmr_cache_control {
    default                "public, max-age=31536000, immutable";
    ~^text/html            "public, max-age=0, must-revalidate";
    ~^application/xml      "public, max-age=3600";
    ~^text/xml             "public, max-age=3600";
}
MAP

cat > /etc/nginx/sites-available/hunyamunya <<'NGINX'
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name hunyamunyarecords.com www.hunyamunyarecords.com _;
    root /var/www/hunyamunya;
    index index.html;

    # Deny dotfiles except /.well-known/ (ACME challenges, etc.). Also hides
    # the .nginx-redirects.conf snippet from being served over HTTP.
    location ~ /\.(?!well-known) { deny all; }

    # Block exposing the WP-import migration dump if it ever ends up rsynced.
    location ^~ /migration/ { deny all; }

    # Legacy WordPress redirects (path + query-string), generated by
    # site/scripts/redirects-build-nginx.ts. The include must resolve; the
    # empty-file touch above guarantees that even on a fresh VPS.
    include /var/www/hunyamunya/.nginx-redirects.conf;

    # Long-cache immutable Next.js assets.
    location /_next/ { expires 1y; add_header Cache-Control "public, immutable"; }

    # Strip a trailing .html in the visible URL (static export exposes them
    # otherwise). 301 is safe because the try_files below serves the .html
    # content at the cleaned URL.
    if ($request_uri ~ ^/(.*)\.html(\?.*)?$) { return 301 /$1$2; }

    # Static export mapping: /about -> about.html, /artists/rykard -> artists/rykard/index.html
    location / { try_files $uri $uri.html $uri/ =404; }

    # Security headers mirroring the Apache .htaccess rules.
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;
    add_header Cache-Control $hmr_cache_control always;
}
NGINX

ln -sf /etc/nginx/sites-available/hunyamunya /etc/nginx/sites-enabled/hunyamunya
rm -f /etc/nginx/sites-enabled/default

# Narrow sudoers grant: deploy workflow needs to validate + reload nginx
# after rsyncing the redirect snippet. No other root privileges.
cat > /etc/sudoers.d/deploy-nginx <<'SUDO'
deploy ALL=(root) NOPASSWD: /usr/sbin/nginx -t, /bin/systemctl reload nginx
SUDO
chmod 440 /etc/sudoers.d/deploy-nginx

nginx -t
systemctl reload nginx

echo ""
echo "==== base setup done ===="
echo ""
echo "Next: from this same shell, paste the following then hit Enter (replace"
echo "the inner line with the exact contents of your deploy-actions.pub):"
echo ""
echo "echo 'ssh-ed25519 AAAA...your-key-here... deploy-actions' >> /home/deploy/.ssh/authorized_keys"
echo ""
