import Link from "next/link";
import type { Metadata } from "next";
import { buildMetadata, sectionTitle } from "@/lib/seo";
import { SEO } from "@/components/SEO";
import { breadcrumbJsonLd } from "@/lib/jsonld";
import { CopyText } from "@/components/CopyText";
import { UnderwaterLayer, type LaneConfig } from "@/components/UnderwaterLayer";
import { getArtistBySlug, getReleasesByArtistSlug } from "@/lib/content";
import { LISTINGS, PRESS_EMAIL, PRESS_QUOTES, STATIONS } from "@/lib/press-data";
import pandoraStats from "@/data/pandora-stats.json";

const KIT_LANES: LaneConfig[] = [
  { shape: "round", direction: "bt", left: "12%", width: 70,  duration: 110, delay: -18, opacityMod: 0.9 },
  { shape: "long",  direction: "lr", top: "62%",  width: 200, duration: 145, delay: -70, opacityMod: 0.8, mobileHide: true },
];

export function generateMetadata(): Metadata {
  return buildMetadata({
    title: sectionTitle("Rykard press kit"),
    description:
      "Press kit for Rykard: biographies, high-resolution photos and cover art, broadcast history, discography, and press contact.",
    path: "/press/rykard",
  });
}

const BIO_SHORT = `Rykard is the ambient electronic project of Richard Wearing, working from the Lancashire countryside in the north of England. His 2010 debut, Arrive the Radio Beacon, drew support from BBC 6 Music and KCRW, and its centerpiece "North Cormorant Obscurity" has since passed 25 million streams. Three more albums and the four-volume Explorers series have followed on Hunya Munya Records.`;

const BIO_MEDIUM = `Rykard is the ambient electronic project of Richard Wearing, who has recorded from the Lancashire countryside in the north of England since 2010. His debut album, Arrive the Radio Beacon, arrived that year on Hunya Munya Records and travelled a long way for a small record, picking up plays from Tom Robinson on BBC 6 Music, Anne Litt on KCRW, and Morning Becomes Eclectic, along with KEXP, KALX, BBC Radio Bristol, and CBC Radio 2. Its centerpiece, "North Cormorant Obscurity," has since passed 25 million streams.

The full-lengths Luminosity (2016) and Night Towers (2018) followed, then the four-volume Explorers series between 2019 and 2023. The music draws on nature, science fiction, and long-form atmosphere, built from deep low end, slow melodic fragments, and a great deal of space. In December 2025 the label pressed a fifteen-year anniversary 12" of "North Cormorant Obscurity," re-edited and mastered for vinyl with an unreleased B side, "Troup Head." A new album is in the works.`;

const BIO_LONG = `Rykard is the ambient electronic project of Richard Wearing, who has recorded from the Lancashire countryside in the north of England since 2010. The name is a play on his own, and the work has kept the same unhurried character across fifteen years: cinematic, weather-beaten, built from deep low end, slow melodic fragments, and a great deal of space.

His debut album, Arrive the Radio Beacon, was released by Hunya Munya Records in March 2010 and travelled a long way for a small record. Tom Robinson played it on BBC 6 Music. Anne Litt played it repeatedly on KCRW through the spring and summer of that year, and it reached Morning Becomes Eclectic in May. KEXP, KALX, BBC Radio Bristol, and CBC Radio 2 followed, and the album was accepted into Pandora. Its centerpiece, "North Cormorant Obscurity," has since passed 25 million streams, the widest reach of anything on the label.

The full-lengths Luminosity (2016) and Night Towers (2018) followed, then Explorers, a four-volume series released between 2019 and 2023 that gave the longer, more open pieces somewhere to live. Reviewers have called the records "a heady trip into the deepest and warmest electronic bliss-core" and "sublime electronic exploration" (I Heart Noise), and his pre-label release Hell Bent was picked up by Darkfloor in 2009.

In December 2025 Hunya Munya pressed a fifteen-year anniversary 12" of "North Cormorant Obscurity," re-edited and mastered for vinyl by Vinyl Ceremony with an unreleased B side, "Troup Head." A new Rykard album is in the works.`;

type AssetKind = "photo" | "art" | "logo";
type KitAsset = {
  file: string;
  thumb: string;
  label: string;
  kind: AssetKind;
  dims: string;
  size: string;
};

// Generated by scripts/press-kit-assets.ts, which stages the files and prints
// these rows. Re-run it after changing the asset list.
const ASSETS: KitAsset[] = [
  { file: "rykard-press-photo.jpg", thumb: "rykard-press-photo-thumb.jpg", label: "Press photo, current", kind: "photo", dims: "3905x5858", size: "2.0 MB" },
  { file: "rykard-press-photo-2010-1.jpg", thumb: "rykard-press-photo-2010-1-thumb.jpg", label: "Archive photo, 2010", kind: "photo", dims: "2560x1440", size: "245 KB" },
  { file: "rykard-press-photo-2010-2.jpg", thumb: "rykard-press-photo-2010-2-thumb.jpg", label: "Archive photo, 2010", kind: "photo", dims: "2576x1932", size: "866 KB" },
  { file: "rykard-nco-test-pressing-1.jpg", thumb: "rykard-nco-test-pressing-1-thumb.jpg", label: "NCO test pressing on the deck", kind: "photo", dims: "4032x3024", size: "1.8 MB" },
  { file: "rykard-nco-test-pressing-2.jpg", thumb: "rykard-nco-test-pressing-2-thumb.jpg", label: "NCO test pressing, white label", kind: "photo", dims: "3024x4032", size: "1.2 MB" },
  { file: "hmr010-nco-front.jpg", thumb: "hmr010-nco-front-thumb.jpg", label: "North Cormorant Obscurity, front", kind: "art", dims: "5000x5000", size: "2.1 MB" },
  { file: "hmr010-nco-back.jpg", thumb: "hmr010-nco-back-thumb.jpg", label: "North Cormorant Obscurity, back", kind: "art", dims: "5000x5000", size: "2.1 MB" },
  { file: "arrive-the-radio-beacon-cover.jpg", thumb: "arrive-the-radio-beacon-cover-thumb.jpg", label: "Arrive the Radio Beacon", kind: "art", dims: "2048x2048", size: "474 KB" },
  { file: "luminosity-cover.jpg", thumb: "luminosity-cover-thumb.jpg", label: "Luminosity", kind: "art", dims: "3386x3386", size: "1.8 MB" },
  { file: "night-towers-cover.jpg", thumb: "night-towers-cover-thumb.jpg", label: "Night Towers", kind: "art", dims: "1200x1079", size: "155 KB" },
  { file: "hmr010-nco-vinyl-a.png", thumb: "hmr010-nco-vinyl-a-thumb.png", label: "NCO vinyl, A side", kind: "art", dims: "900x900", size: "263 KB" },
  { file: "hmr010-nco-vinyl-b.png", thumb: "hmr010-nco-vinyl-b-thumb.png", label: "NCO vinyl, B side", kind: "art", dims: "900x900", size: "264 KB" },
  { file: "hunya-munya-logo.png", thumb: "hunya-munya-logo-thumb.png", label: "Hunya Munya Records logo", kind: "logo", dims: "900x600", size: "28 KB" },
];

// The current press photo doubles as the page's opening image. Named rather
// than indexed so reordering ASSETS cannot silently blank the hero.
const HERO = ASSETS.find((a) => a.file === "rykard-press-photo.jpg")!;

const ASSET_GROUPS: { kind: AssetKind; title: string }[] = [
  { kind: "photo", title: "Photography" },
  { kind: "art", title: "Cover art" },
  { kind: "logo", title: "Label" },
];

function words(s: string): number {
  return s.trim().split(/\s+/).length;
}

export default function RykardPressKitPage() {
  const artist = getArtistBySlug("rykard");
  const releases = getReleasesByArtistSlug("rykard");
  const monthly = pandoraStats.rykard?.monthlyListeners;

  // Only the plays that are actually his. The stations list covers the whole
  // roster, so Catnip & Claws on Radio Norfolk does not belong in his kit.
  const stations = STATIONS.map((st) => ({
    ...st,
    plays: st.plays.filter((p) => p.artist.toLowerCase().includes("rykard")),
  })).filter((st) => st.plays.length > 0);

  const highlights = artist?.data.intro?.highlights ?? [];

  const QUICK_FACTS = [
    { term: "Real name", detail: "Richard Wearing" },
    { term: "Based", detail: "Lancashire, England" },
    { term: "Genres", detail: (artist?.data.genres ?? []).join(", ") },
    { term: "Label", detail: `Hunya Munya Records, since ${artist?.data.intro?.est_year ?? 2010}` },
  ].filter((f) => f.detail);

  const linkFields: { label: string; url?: string }[] = [
    { label: "Spotify", url: artist?.data.links?.spotify },
    { label: "Bandcamp", url: artist?.data.links?.bandcamp },
    { label: "Website", url: artist?.data.links?.website },
  ];
  const links = linkFields.filter((l): l is { label: string; url: string } => Boolean(l.url));

  return (
    <>
      <SEO
        jsonLd={[
          breadcrumbJsonLd([
            { name: "Home", path: "/" },
            { name: "Press", path: "/press" },
            { name: "Rykard", path: "/press/rykard" },
          ]),
        ]}
      />

      <UnderwaterLayer zone="lookup" lanes={KIT_LANES} flushTop>
        <section className="border-b border-rule pb-16 pt-20 md:pb-20 md:pt-28">
          <div
            className="mb-5 flex items-center gap-3 text-[11px] uppercase text-[color:var(--hm-accent)]"
            style={{ letterSpacing: "0.22em" }}
          >
            <span className="block h-px w-6 bg-current" />
            Press kit
          </div>
          <h1 className="text-[clamp(40px,5.5vw,84px)] font-normal leading-[0.98] tracking-tighter text-paper">
            Rykard.
          </h1>
          {/* The lead photo is a portrait, so it sits in its own column rather
              than being cropped to a letterbox across the full width. */}
          <div className="mt-10 grid grid-cols-1 gap-10 md:mt-14 md:grid-cols-[minmax(0,360px)_1fr] md:gap-14">
            <figure>
              <a
                href={`/press/rykard/${HERO.file}`}
                download
                className="group block overflow-hidden border border-neutral-800"
              >
                <img
                  src={`/press/rykard/${HERO.thumb}`}
                  alt="Rykard"
                  className="block h-auto w-full transition-transform duration-500 group-hover:scale-[1.02]"
                  loading="eager"
                />
              </a>
              <figcaption
                className="mt-3 flex flex-wrap items-baseline gap-x-3 text-[10px] uppercase text-muted tabular-nums"
                style={{ letterSpacing: "0.2em" }}
              >
                <span className="text-paper-dim">Rykard</span>
                <span>
                  {HERO.dims} &middot; {HERO.size}
                </span>
                <a
                  href={`/press/rykard/${HERO.file}`}
                  download
                  className="text-[color:var(--hm-accent)] underline-offset-4 hover:underline"
                >
                  Download &darr;
                </a>
              </figcaption>
            </figure>

            <div>
              <p className="max-w-[62ch] font-serif text-[20px] italic leading-[1.5] text-paper-dim">
                Biographies, high-resolution photography and cover art, broadcast
                history, and discography. Everything here is cleared for editorial
                use. For interviews, review copies, or anything not on this page,
                write to{" "}
                <a
                  href={`mailto:${PRESS_EMAIL}`}
                  className="not-italic text-paper underline-offset-4 hover:text-[color:var(--hm-accent)] hover:underline"
                >
                  {PRESS_EMAIL}
                </a>
                .
              </p>

              {/* The answers to the first four questions anyone writing a
                  listing has to look up, so they never have to read the bio
                  to find them. */}
              <dl className="mt-10 grid grid-cols-1 gap-x-10 gap-y-5 border-t border-rule pt-8 sm:grid-cols-2">
                {QUICK_FACTS.map((f) => (
                  <div key={f.term}>
                    <dt
                      className="text-[10px] uppercase text-muted"
                      style={{ letterSpacing: "0.22em" }}
                    >
                      {f.term}
                    </dt>
                    <dd className="mt-1.5 text-[14px] leading-snug text-paper">
                      {f.detail}
                    </dd>
                  </div>
                ))}
                {links.length > 0 ? (
                  <div className="sm:col-span-2">
                    <dt
                      className="text-[10px] uppercase text-muted"
                      style={{ letterSpacing: "0.22em" }}
                    >
                      Listen
                    </dt>
                    <dd className="mt-1.5 text-[14px] text-paper">
                      {links.map((l, i) => (
                        <span key={l.url}>
                          <a
                            href={l.url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="underline-offset-4 hover:text-[color:var(--hm-accent)] hover:underline"
                          >
                            {l.label}
                          </a>
                          {i < links.length - 1 ? (
                            <span className="text-muted"> &middot; </span>
                          ) : null}
                        </span>
                      ))}
                    </dd>
                  </div>
                ) : null}
              </dl>
            </div>
          </div>
        </section>

        <section className="grid grid-cols-1 border-b border-rule sm:grid-cols-3">
          {highlights.map((h, i) => (
            <div
              key={h.label}
              className={`px-1 py-8 sm:px-6 ${
                i < highlights.length - 1 ? "sm:border-r sm:border-rule" : ""
              }`}
            >
              <p className="text-[clamp(28px,3.4vw,44px)] leading-none tracking-tighter text-paper tabular-nums">
                {h.num}
              </p>
              <p
                className="mt-3 text-[10px] uppercase text-muted"
                style={{ letterSpacing: "0.22em" }}
              >
                {h.label}
              </p>
            </div>
          ))}
        </section>

        <section className="border-b border-rule py-20 md:py-28">
          <h2 className="mb-3 text-[clamp(28px,3.2vw,44px)] font-normal leading-none tracking-tighter text-paper">
            Biography.
          </h2>
          <p className="mb-10 max-w-[62ch] text-[13px] leading-relaxed text-muted">
            Three lengths, ready to paste. Please credit Hunya Munya Records.
          </p>
          <div className="space-y-10">
            <CopyText label="Short" wordCount={words(BIO_SHORT)} text={BIO_SHORT} />
            <CopyText label="Medium" wordCount={words(BIO_MEDIUM)} text={BIO_MEDIUM} />
            <CopyText label="Full" wordCount={words(BIO_LONG)} text={BIO_LONG} />
          </div>
        </section>

        <section className="border-b border-rule py-20 md:py-28">
          <h2 className="mb-3 text-[clamp(28px,3.2vw,44px)] font-normal leading-none tracking-tighter text-paper">
            Assets.
          </h2>
          <p className="mb-10 max-w-[62ch] text-[13px] leading-relaxed text-muted">
            Click any image to download it at full size. Photography and artwork
            are cleared for editorial use with credit.
          </p>
          <div className="space-y-12">
            {ASSET_GROUPS.map((group) => {
              const items = ASSETS.filter((a) => a.kind === group.kind);
              if (items.length === 0) return null;
              return (
                <div key={group.kind}>
                  <h3
                    className="mb-4 border-b border-rule pb-3 text-[10px] uppercase text-muted"
                    style={{ letterSpacing: "0.22em" }}
                  >
                    {group.title}
                  </h3>
                  <ul className="grid grid-cols-2 gap-x-5 gap-y-8 sm:grid-cols-3 lg:grid-cols-4">
                    {items.map((a) => (
                      <li key={a.file}>
                        <a
                          href={`/press/rykard/${a.file}`}
                          download
                          className="group block"
                        >
                          <div className="aspect-[4/3] overflow-hidden border border-neutral-800 bg-neutral-950">
                            <img
                              src={`/press/rykard/${a.thumb}`}
                              alt={a.label}
                              // The transparent PNGs are a record and a logo,
                              // both of which get cropped into nonsense by
                              // object-cover. Photographs want the opposite.
                              className={
                                a.file.endsWith(".png")
                                  ? "h-full w-full object-contain p-6 transition-transform duration-500 group-hover:scale-[1.03]"
                                  : "h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.03]"
                              }
                              loading="lazy"
                            />
                          </div>
                          <p className="mt-3 text-[13px] leading-snug text-paper">
                            {a.label}
                          </p>
                          <p className="mt-1 text-[11px] text-paper-dim tabular-nums">
                            {a.dims} &middot; {a.size} &middot;{" "}
                            {a.file.split(".").pop()?.toUpperCase()}
                          </p>
                          <span
                            className="mt-2 inline-block text-[10px] uppercase text-[color:var(--hm-accent)] underline-offset-4 group-hover:underline"
                            style={{ letterSpacing: "0.2em" }}
                          >
                            Download &darr;
                          </span>
                        </a>
                      </li>
                    ))}
                  </ul>
                </div>
              );
            })}
          </div>
        </section>

        <section className="border-b border-rule py-20 md:py-28">
          <h2 className="mb-3 text-[clamp(28px,3.2vw,44px)] font-normal leading-none tracking-tighter text-paper">
            Discography.
          </h2>
          <p className="mb-10 max-w-[62ch] text-[13px] leading-relaxed text-muted">
            {releases.length} releases on Hunya Munya Records
            {monthly
              ? `, ${Math.round(monthly / 1000)}k monthly listeners on Pandora`
              : ""}
            .
          </p>
          <ul className="divide-y divide-rule">
            {releases.map((r) => (
              <li
                key={r.urlPath}
                className="grid grid-cols-[70px_1fr_auto] items-baseline gap-5 py-4 text-[14px] md:grid-cols-[90px_1fr_auto]"
              >
                <span
                  className="text-[10px] uppercase text-muted tabular-nums"
                  style={{ letterSpacing: "0.12em" }}
                >
                  {r.data.release_date?.slice(0, 4)}
                </span>
                <Link
                  href={r.urlPath}
                  className="text-paper underline-offset-4 hover:text-[color:var(--hm-accent)] hover:underline"
                >
                  <em className="font-serif italic">{r.data.title}</em>
                </Link>
                <span
                  className="text-[10px] uppercase text-muted"
                  style={{ letterSpacing: "0.18em" }}
                >
                  {r.data.catalog_number}
                </span>
              </li>
            ))}
          </ul>
        </section>

        <section className="border-b border-rule py-20 md:py-28">
          <h2 className="mb-3 text-[clamp(28px,3.2vw,44px)] font-normal leading-none tracking-tighter text-paper">
            Broadcast.
          </h2>
          <p className="mb-10 max-w-[62ch] text-[13px] leading-relaxed text-muted">
            Documented plays only. Where a source is linked, it is the station
            tracklist or a recording of the broadcast.
          </p>
          <div className="space-y-12">
            {stations.map((st) => (
              <div key={st.name}>
                <div className="mb-4 flex items-baseline justify-between gap-6 border-b border-rule pb-3">
                  <h3 className="font-serif text-[clamp(18px,2vw,26px)] leading-none text-paper">
                    {st.name}
                  </h3>
                  <p
                    className="text-[10px] uppercase text-muted"
                    style={{ letterSpacing: "0.18em" }}
                  >
                    {st.location}
                  </p>
                </div>
                <ul className="divide-y divide-rule">
                  {st.plays.map((p, i) => (
                    <li
                      key={`${st.name}-${i}`}
                      className="grid grid-cols-[90px_1fr_auto] items-baseline gap-5 py-3 text-[14px] md:grid-cols-[110px_1fr_auto]"
                    >
                      <span
                        className="text-[10px] uppercase text-muted tabular-nums"
                        style={{ letterSpacing: "0.12em" }}
                      >
                        {p.date}
                      </span>
                      <span className="text-paper">
                        {p.host ? (
                          <span className="text-paper-dim">{p.host}: </span>
                        ) : null}
                        {p.track ? (
                          <em className="font-serif italic">
                            &ldquo;{p.track}&rdquo;
                          </em>
                        ) : (
                          <span className="text-paper-dim">{p.note}</span>
                        )}
                      </span>
                      {p.url ? (
                        <a
                          href={p.url}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-[10px] uppercase text-[color:var(--hm-accent)] underline-offset-4 hover:underline"
                          style={{ letterSpacing: "0.2em" }}
                        >
                          Source &rarr;
                        </a>
                      ) : (
                        <span aria-hidden="true" />
                      )}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </section>

        <section className="border-b border-rule py-20 md:py-28">
          <h2 className="mb-10 text-[clamp(28px,3.2vw,44px)] font-normal leading-none tracking-tighter text-paper">
            Press.
          </h2>
          <div className="space-y-10">
            {PRESS_QUOTES.map((q) => (
              <figure
                key={`${q.source}-${q.date}`}
                className="border-t border-rule pt-5"
              >
                <blockquote className="max-w-[64ch] font-serif text-[clamp(18px,2vw,24px)] italic leading-[1.45] text-paper">
                  &ldquo;{q.quote}&rdquo;
                </blockquote>
                <figcaption
                  className="mt-4 flex flex-wrap items-baseline gap-x-3 text-[10px] uppercase text-muted"
                  style={{ letterSpacing: "0.2em" }}
                >
                  <span className="text-paper-dim">{q.source}</span>
                  <span>{q.date}</span>
                  <span>{q.release}</span>
                  {q.url ? (
                    <a
                      href={q.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-[color:var(--hm-accent)] underline-offset-4 hover:underline"
                    >
                      Read &rarr;
                    </a>
                  ) : null}
                </figcaption>
              </figure>
            ))}
          </div>
        </section>

        <section className="py-20 md:py-28">
          <h2 className="mb-10 text-[clamp(28px,3.2vw,44px)] font-normal leading-none tracking-tighter text-paper">
            Contact and links.
          </h2>
          <div className="grid grid-cols-1 gap-10 md:grid-cols-2">
            <div>
              <p
                className="mb-3 text-[10px] uppercase text-muted"
                style={{ letterSpacing: "0.22em" }}
              >
                Press contact
              </p>
              <a
                href={`mailto:${PRESS_EMAIL}`}
                className="font-serif text-[clamp(20px,2.4vw,30px)] italic text-paper underline-offset-4 hover:text-[color:var(--hm-accent)] hover:underline"
              >
                {PRESS_EMAIL}
              </a>
              <p className="mt-4 max-w-[46ch] text-[13px] leading-relaxed text-muted">
                Artist page:{" "}
                <Link
                  href="/artists/rykard"
                  className="underline-offset-4 hover:text-paper-dim hover:underline"
                >
                  hunyamunyarecords.com/artists/rykard
                </Link>
              </p>
            </div>
            <div>
              <p
                className="mb-3 text-[10px] uppercase text-muted"
                style={{ letterSpacing: "0.22em" }}
              >
                Listed on
              </p>
              <p className="text-[12px] leading-relaxed text-paper-dim">
                {LISTINGS.map((l, i) => (
                  <span key={l.url}>
                    <a
                      href={l.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="underline-offset-4 hover:text-paper hover:underline"
                    >
                      {l.label}
                    </a>
                    {i < LISTINGS.length - 1 ? (
                      <span className="text-muted"> &middot; </span>
                    ) : null}
                  </span>
                ))}
              </p>
            </div>
          </div>
        </section>
      </UnderwaterLayer>
    </>
  );
}
